### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by sunville** [HackerHouseYT/OpenAI-NEAT#7]
I use neat-8.0 version package.

I run the script like this:
./gym_solver.py --episodes=3 --generations=100 --num-cores=1 --max-steps=10

No matter what the max-steps I set I always get this error message in generation 1

Traceback (most recent call last):
  File "./gym_solver.py", line 112, in <module>
    train_network(my_env)
  File "./gym_solver.py", line 82, in train_network
    pop.run(pe.evaluate, args.generations)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/neat/population.py", line 186, in run
    fitness_function(population)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/neat/parallel.py", line 22, in evaluate
    genome.fitness = job.get(timeout=self.timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by sunville** [comment]
And this problem only happens in simulating 'Breakout-v0'
