### ISSUE TITLE
AttributeError: 'str' object has no attribute 'stagnation_type'

### ISSUE THREAD

**Issue by BeholdenArt** [HackerHouseYT/OpenAI-NEAT#9]
# Command ran : >python something.py --max-steps=1000 --episodes=10 --generations=50 --render

Input Nodes: 4
Output Nodes: 2

**Traceback (most recent call last):**
  File "something.py", line 111, in <module>
    train_network(my_env)
  File "something.py", line 72, in train_network
    pop = population.Population(config_path)
  File "D:\Anaconda\envs\Tensor-GPU\lib\site-packages\neat\population.py", line 26, in __init__
    stagnation = config.stagnation_type(config.stagnation_config, self.reporters)
AttributeError: 'str' object has no attribute 'stagnation_type'

**Comment by aaselivanov** [comment]
Try to install specific version of neat-python (pip install neat-python==0.8), it seems like an error in this package.
Such step worked for me, hope you'll succeed too (I see the date, but this answer might be useful for someone else).
